name: Publish MCP Package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'pypi'
        type: choice
        options:
          - pypi
          - testpypi

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Set up Node.js for DXT CLI
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        npm install -g @anthropic-ai/dxt
    
    - name: Build Python package
      run: python -m build
    
    - name: Create DXT manifest
      run: |
        cat > manifest.json << 'EOF'
        {
          "dxt_version": "0.1.1",
          "name": "github-projects-mcp",
          "version": "${{ github.ref_name }}",
          "description": "A Model Context Protocol server for GitHub Projects",
          "long_description": "This package provides a Model Context Protocol (MCP) server for managing GitHub Projects, allowing users to interact with GitHub Projects through a standardized API.",
          "author": {
            "name": "Red Duck Labs, LLC",
            "email": "contact@redducklabs.com",
            "url": "https://github.com/redducklabs"
          },
          "server": {
            "type": "python",
            "entry_point": "github_projects_mcp/server.py",
            "mcp_config": {
              "command": "python",
              "args": ["-m", "github_projects_mcp.server"]
            }
          },
          "user_config": {
            "GITHUB_TOKEN": {
              "title": "GitHub Token",
              "type": "string",
              "description": "GitHub Personal Access Token with project permissions",
              "sensitive": true,
              "required": true
            },
            "API_MAX_RETRIES": {
              "title": "Max Retries",
              "type": "string",
              "description": "Maximum retries for rate-limited requests",
              "default": "3"
            },
            "API_RETRY_DELAY": {
              "title": "Retry Delay",
              "type": "string",
              "description": "Delay in seconds between retries", 
              "default": "60"
            }
          }
        }
        EOF
    
    - name: Build DXT package
      run: dxt pack
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
    
    - name: Upload DXT package
      uses: actions/upload-artifact@v4
      with:
        name: dxt-package
        path: "*.dxt"

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment || 'pypi' }}
      url: ${{ github.event.inputs.environment == 'testpypi' && 'https://test.pypi.org/p/github-projects-mcp' || 'https://pypi.org/p/github-projects-mcp' }}
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    
    - name: Publish to TestPyPI
      if: github.event.inputs.environment == 'testpypi'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: dist/
    
    - name: Publish to PyPI
      if: github.event.inputs.environment == 'pypi' || github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/